/**
 * Catálogo de productos de seguro paramétrico — Lumina Protocol
 * 6 productos con configuración completa hardcodeada
 */

const PRODUCTS = {
  "LIQSHIELD-001": {
    id: "LIQSHIELD-001",
    name: "Liquidation Shield",
    description: "Protects against forced liquidation from price drops",
    triggerType: "PRICE_DROP_PCT",
    availableAssets: ["ETH", "BTC"],
    thresholdOptions: [1000, 1500, 2000, 2500, 3000],
    thresholdUnit: "bps",
    sustainedPeriod: 1800,
    waitingPeriod: 86400,
    deductibleBps: 500,
    minDurationDays: 7,
    maxDurationDays: 90,
    coolingOffPeriod: 7200,
    baseRateBps: 200,
    minCoverageUSDC: 100,
    maxCoverageUSDC: 100000,
    minPremiumUSDC: 10,
    exclusions: [
      "Pre-existing positions with health factor < 1.2 at purchase",
      "Liquidations caused by oracle manipulation",
      "Voluntary position closure by the insured",
    ],
  },

  "DEPEG-USDC-001": {
    id: "DEPEG-USDC-001",
    name: "USDC Depeg Cover",
    description: "Protects against USDC losing its dollar peg",
    triggerType: "PRICE_BELOW",
    availableAssets: ["USDC"],
    thresholdOptions: [9900, 9700, 9500, 9000],
    thresholdUnit: "price_4decimals",
    sustainedPeriod: 14400,
    waitingPeriod: 172800,
    deductibleBps: 300,
    minDurationDays: 14,
    maxDurationDays: 365,
    coolingOffPeriod: 7200,
    baseRateBps: 100,
    minCoverageUSDC: 100,
    maxCoverageUSDC: 500000,
    minPremiumUSDC: 10,
    supportsAutoRenew: true,
    stablecoinRiskMultiplier: 1.0,
    exclusions: [
      "Depeg caused by sanctions or regulatory action against Circle",
      "Temporary depeg lasting less than the sustained period",
    ],
  },

  "DEPEG-USDT-001": {
    id: "DEPEG-USDT-001",
    name: "USDT Depeg Cover",
    description: "Protects against USDT losing its dollar peg",
    triggerType: "PRICE_BELOW",
    availableAssets: ["USDT"],
    thresholdOptions: [9900, 9700, 9500, 9000],
    thresholdUnit: "price_4decimals",
    sustainedPeriod: 14400,
    waitingPeriod: 172800,
    deductibleBps: 300,
    minDurationDays: 14,
    maxDurationDays: 365,
    coolingOffPeriod: 7200,
    baseRateBps: 100,
    minCoverageUSDC: 100,
    maxCoverageUSDC: 500000,
    minPremiumUSDC: 10,
    supportsAutoRenew: true,
    stablecoinRiskMultiplier: 1.3,
    exclusions: [
      "Depeg caused by sanctions or regulatory action against Tether",
      "Temporary depeg lasting less than the sustained period",
    ],
  },

  "DEPEG-DAI-001": {
    id: "DEPEG-DAI-001",
    name: "DAI Depeg Cover",
    description: "Protects against DAI losing its dollar peg",
    triggerType: "PRICE_BELOW",
    availableAssets: ["DAI"],
    thresholdOptions: [9900, 9700, 9500, 9000],
    thresholdUnit: "price_4decimals",
    sustainedPeriod: 14400,
    waitingPeriod: 172800,
    deductibleBps: 300,
    minDurationDays: 14,
    maxDurationDays: 365,
    coolingOffPeriod: 7200,
    baseRateBps: 100,
    minCoverageUSDC: 100,
    maxCoverageUSDC: 500000,
    minPremiumUSDC: 10,
    supportsAutoRenew: true,
    stablecoinRiskMultiplier: 1.2,
    exclusions: [
      "Depeg caused by MakerDAO governance attack",
      "Temporary depeg lasting less than the sustained period",
    ],
  },

  "ILPROT-001": {
    id: "ILPROT-001",
    name: "Impermanent Loss Protection",
    description: "Protects LP positions against impermanent loss from price divergence",
    triggerType: "PRICE_DIVERGENCE",
    availableAssets: ["ETH/USDC", "BTC/USDC", "ETH/BTC"],
    thresholdOptions: [1500, 2000, 3000, 5000],
    thresholdUnit: "bps",
    sustainedPeriod: 7200,
    waitingPeriod: 86400,
    deductibleBps: 800,
    minDurationDays: 14,
    maxDurationDays: 60,
    coolingOffPeriod: 7200,
    baseRateBps: 300,
    minCoverageUSDC: 100,
    maxCoverageUSDC: 100000,
    minPremiumUSDC: 10,
    exclusions: [
      "IL from rug pulls or exploits on the underlying DEX",
      "Positions entered after policy activation",
    ],
  },

  "GASSPIKE-001": {
    id: "GASSPIKE-001",
    name: "Gas Spike Shield",
    description: "Protects against excessive gas costs during network congestion",
    triggerType: "GAS_ABOVE",
    availableAssets: [],
    thresholdOptions: [50, 100, 200, 500],
    thresholdUnit: "gwei",
    sustainedPeriod: 900,
    waitingPeriod: 43200,
    deductibleBps: 1000,
    minDurationDays: 7,
    maxDurationDays: 30,
    coolingOffPeriod: 7200,
    baseRateBps: 150,
    minCoverageUSDC: 100,
    maxCoverageUSDC: 50000,
    minPremiumUSDC: 10,
    exclusions: [
      "Gas spikes caused by the insured's own transactions",
      "Network upgrades or planned maintenance",
    ],
  },

  "SLIPPAGE-001": {
    id: "SLIPPAGE-001",
    name: "Slippage Protection",
    description: "Protects against unexpected slippage on large trades",
    triggerType: "PRICE_DROP_PCT",
    availableAssets: ["ETH", "BTC"],
    thresholdOptions: [200, 300, 500, 1000],
    thresholdUnit: "bps",
    sustainedPeriod: 0,
    waitingPeriod: 3600,
    deductibleBps: 300,
    minDurationDays: 1,
    maxDurationDays: 7,
    coolingOffPeriod: 1800,
    baseRateBps: 100,
    minCoverageUSDC: 100,
    maxCoverageUSDC: 100000,
    minPremiumUSDC: 10,
    exclusions: [
      "Slippage from low-liquidity tokens not in the coverage",
      "Intentional market manipulation by the insured",
    ],
  },

  "BRIDGE-001": {
    id: "BRIDGE-001",
    name: "Bridge Failure Cover",
    description: "Protects against bridge transaction failures or excessive delays",
    triggerType: "TIME_BASED",
    availableAssets: [],
    thresholdOptions: [6, 12, 24, 48],
    thresholdUnit: "hours",
    sustainedPeriod: 0,
    waitingPeriod: 3600,
    deductibleBps: 500,
    minDurationDays: 1,
    maxDurationDays: 7,
    coolingOffPeriod: 1800,
    baseRateBps: 200,
    minCoverageUSDC: 100,
    maxCoverageUSDC: 200000,
    minPremiumUSDC: 10,
    supportedBridges: ["base-bridge", "across", "stargate", "hop"],
    exclusions: [
      "Delays under the threshold time",
      "Bridge exploits or hacks (covered by separate product)",
    ],
  },
};

// Chainlink price feeds en Base mainnet
const CHAINLINK_FEEDS = {
  ETH: "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70",
  BTC: "0x64c911996D3c6aC71f9b455B1E8E7266BcbD848F",
  USDC: "0x7e860098F58bBFC8648a4311b374B1D669a2bc6B",
  USDT: "0xf19d560eB8d2ADf07BD6D13ed03e1D11215721F9",
  DAI: "0x591e79239a7d679378eC8c847e5038150364C78F",
};

module.exports = { PRODUCTS, CHAINLINK_FEEDS };
